# espanso docs can be found at: https://espanso.org/docs/

matches:
  - trigger: ':date'
    replace: '{{today}}'
    label:  German date formatting.
    vars:
      - name: today
        type: date
        params:
          format: '%d.%m.%Y'

  - trigger: ':iso-'
    replace: '{{today}}'
    label: ISO date (using '%Y-%m-%d').
    vars:
      - name: today
        type: date
        params:
          format: '%Y-%m-%d'

  - trigger: ':iso_'
    replace: '{{today}}'
    label: Date for file tagging (using '%y%m%d_').
    vars:
      - name: today
        type: date
        params:
          format: '%y%m%d_'

