source_directories:
    - /var/snap/nextcloud/common/nextcloud/data/fynn/files/

repositories:
    - path: /backups/data
      label: local
    - path: ssh://storage/home/data
      label: storage_box

keep_daily: 7
keep_weekly: 4
keep_monthly: 6

before_backup:
    - /snap/bin/nextcloud.occ maintenance:mode --on

after_backup:
    - /snap/bin/nextcloud.occ maintenance:mode --off
    # - /usr/bin/rsync -avz -e 'ssh -p23' /backups/data storage:/home/data

