# TODO don't break lists over pages: https://tex.stackexchange.com/a/86063

verbosity: INFO
fail-if-warnings: false
log-file: ${HOME}/.local/state/pandoc/pandoc.log

metadata-files:
  - ${.}/../style/yaml/a4.yaml
  - ${.}/../style/yaml/links.yaml
  - ${.}/../style/yaml/font.yaml

include-in-header:
  - ${.}/../style/tex/centered_figs.tex
  - ${.}/../style/tex/deep_bullet_lists.tex

filters:
  - ${.}/../filters/transclude.lua
  - ${.}/../filters/plantuml.py
  - ${.}/../filters/mermaid.py

citeproc: true
csl: ${.}/../style/citations/ieee.csl
