---
geometry:
  - paper=a4paper
  - margin=2.5cm

fontsize: 12
fontfamily: roboto
fontfamilyoptions: sfdefault
linestretch: 1.2

hyperrefoptions:
  - linktoc=all
  - pdfwindowui

urlcolor: blue
linkcolor: darkgray
---
